<?php
if (!defined('ABSPATH')) {
    exit;
}

class AIBIMA_Renderer {
    public static function invoice($invoice, $show_actions = true) {
        $currency = $invoice['currency'] ?? 'INR';
        $customer = is_array($invoice['customer'] ?? null) ? $invoice['customer'] : array();
        $business = is_array($invoice['business'] ?? null) ? $invoice['business'] : array();
        $items = is_array($invoice['items'] ?? null) ? $invoice['items'] : array();
        $tax_breakup = is_array($invoice['tax_breakup'] ?? null) ? $invoice['tax_breakup'] : array();

        ob_start();
        ?>
        <article class="aibill-invoice-card" data-aibill-invoice-card>
            <?php if ($show_actions): ?>
                <div class="aibill-print-actions no-print">
                    <button type="button" class="aibill-btn aibill-btn-primary" data-aibill-print><?php esc_html_e('Print', 'aibill-maker'); ?></button>
                    <button type="button" class="aibill-btn aibill-btn-soft" data-aibill-copy><?php esc_html_e('Copy invoice text', 'aibill-maker'); ?></button>
                </div>
            <?php endif; ?>
            <header class="aibill-invoice-head">
                <div>
                    <span class="aibill-pill"><?php echo esc_html(strtoupper($invoice['invoice_type'] ?? 'invoice')); ?></span>
                    <h2><?php echo esc_html($invoice['invoice_number'] ?? 'INV'); ?></h2>
                    <p><?php echo esc_html__('Generated by AiBill Maker', 'aibill-maker'); ?> · <?php echo esc_html(ucfirst($invoice['source'] ?? 'local')); ?></p>
                </div>
                <div class="aibill-total-badge">
                    <span><?php esc_html_e('Total due', 'aibill-maker'); ?></span>
                    <strong><?php echo esc_html(AIBIMA_Parser::money($invoice['grand_total'] ?? 0, $currency)); ?></strong>
                </div>
            </header>

            <section class="aibill-two-col">
                <div>
                    <h3><?php esc_html_e('From', 'aibill-maker'); ?></h3>
                    <?php self::party($business); ?>
                </div>
                <div>
                    <h3><?php esc_html_e('Bill to', 'aibill-maker'); ?></h3>
                    <?php self::party($customer); ?>
                </div>
            </section>

            <section class="aibill-meta-grid">
                <div><span><?php esc_html_e('Issue date', 'aibill-maker'); ?></span><b><?php echo esc_html($invoice['issue_date'] ?? ''); ?></b></div>
                <div><span><?php esc_html_e('Due date', 'aibill-maker'); ?></span><b><?php echo esc_html($invoice['due_date'] ?? ''); ?></b></div>
                <div><span><?php esc_html_e('Currency', 'aibill-maker'); ?></span><b><?php echo esc_html($currency); ?></b></div>
            </section>

            <table class="aibill-items-table">
                <thead>
                    <tr>
                        <th><?php esc_html_e('Item', 'aibill-maker'); ?></th>
                        <th><?php esc_html_e('Qty', 'aibill-maker'); ?></th>
                        <th><?php esc_html_e('Rate', 'aibill-maker'); ?></th>
                        <th><?php esc_html_e('Tax', 'aibill-maker'); ?></th>
                        <th><?php esc_html_e('Total', 'aibill-maker'); ?></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($items as $item): ?>
                    <tr>
                        <td>
                            <strong><?php echo esc_html($item['name'] ?? ''); ?></strong>
                            <?php if (!empty($item['description'])): ?><small><?php echo esc_html($item['description']); ?></small><?php endif; ?>
                            <?php if (!empty($item['hsn_sac'])): ?><small><?php esc_html_e('HSN/SAC:', 'aibill-maker'); ?> <?php echo esc_html($item['hsn_sac']); ?></small><?php endif; ?>
                        </td>
                        <td><?php echo esc_html(number_format((float) ($item['quantity'] ?? 0), 3)); ?> <?php echo esc_html($item['unit'] ?? ''); ?></td>
                        <td><?php echo esc_html(AIBIMA_Parser::money($item['unit_price'] ?? 0, $currency)); ?></td>
                        <td><?php echo esc_html(number_format((float) ($item['tax_rate'] ?? 0), 2)); ?>%</td>
                        <td><?php echo esc_html(AIBIMA_Parser::money($item['line_total'] ?? 0, $currency)); ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

            <section class="aibill-summary">
                <div><span><?php esc_html_e('Subtotal', 'aibill-maker'); ?></span><strong><?php echo esc_html(AIBIMA_Parser::money($invoice['subtotal'] ?? 0, $currency)); ?></strong></div>
                <?php if (!empty($tax_breakup['cgst']) || !empty($tax_breakup['sgst'])): ?>
                    <div><span><?php esc_html_e('CGST', 'aibill-maker'); ?></span><strong><?php echo esc_html(AIBIMA_Parser::money($tax_breakup['cgst'] ?? 0, $currency)); ?></strong></div>
                    <div><span><?php esc_html_e('SGST', 'aibill-maker'); ?></span><strong><?php echo esc_html(AIBIMA_Parser::money($tax_breakup['sgst'] ?? 0, $currency)); ?></strong></div>
                <?php elseif (!empty($tax_breakup['igst'])): ?>
                    <div><span><?php esc_html_e('IGST', 'aibill-maker'); ?></span><strong><?php echo esc_html(AIBIMA_Parser::money($tax_breakup['igst'] ?? 0, $currency)); ?></strong></div>
                <?php else: ?>
                    <div><span><?php esc_html_e('Tax', 'aibill-maker'); ?></span><strong><?php echo esc_html(AIBIMA_Parser::money($invoice['tax_total'] ?? 0, $currency)); ?></strong></div>
                <?php endif; ?>
                <div class="aibill-grand"><span><?php esc_html_e('Grand total', 'aibill-maker'); ?></span><strong><?php echo esc_html(AIBIMA_Parser::money($invoice['grand_total'] ?? 0, $currency)); ?></strong></div>
            </section>

            <section class="aibill-notes-grid">
                <?php if (!empty($invoice['notes'])): ?><div><h3><?php esc_html_e('Notes', 'aibill-maker'); ?></h3><?php echo wp_kses_post(wpautop($invoice['notes'])); ?></div><?php endif; ?>
                <?php if (!empty($invoice['terms'])): ?><div><h3><?php esc_html_e('Terms', 'aibill-maker'); ?></h3><?php echo wp_kses_post(wpautop($invoice['terms'])); ?></div><?php endif; ?>
                <?php if (!empty($invoice['payment_instructions'])): ?><div><h3><?php esc_html_e('Payment instructions', 'aibill-maker'); ?></h3><?php echo wp_kses_post(wpautop($invoice['payment_instructions'])); ?></div><?php endif; ?>
            </section>
        </article>
        <?php
        return ob_get_clean();
    }

    private static function party($party) {
        $name = $party['name'] ?? $party['business_name'] ?? '';
        if ($name === '') {
            $name = __('Not specified', 'aibill-maker');
        }
        echo '<p><strong>' . esc_html($name) . '</strong></p>';
        foreach (array('gstin' => __('GSTIN', 'aibill-maker'), 'email' => __('Email', 'aibill-maker'), 'phone' => __('Phone', 'aibill-maker'), 'address' => __('Address', 'aibill-maker')) as $key => $label) {
            if (!empty($party[$key])) {
                echo '<p><span>' . esc_html($label) . ':</span> ' . esc_html($party[$key]) . '</p>';
            }
        }
    }
}
